server:
  port: 3000
spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: infuse-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #  profiles:
#    active: dev
  application:
    name: infuse-tecnologia
  datasource:
    url: jdbc:postgresql://localhost:5432/creditos_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
